version: '2'
services:
    postgis:
        build: Dockerfiles/postgis/
        hostname: postgis
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql
    merkator:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/opt/merkator
        ports:
            - "8000:8000"
        depends_on:
            - postgis
            - redis
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - postgis
            - merkator
        #volumes:
        #    - ./nginx-default.conf:/etc/nginx/conf.d/default.conf    # Windows don't like folder with dot
        volumes_from:
            - merkator
    redis:
        image: redis
