version: '2'
services:
    postgis:
        image: relin/postgis
    merkator:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - postgis
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - merkator
            - postgis
        volumes:
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - merkator
    redis:
        image: redis
