"""
Django settings for merkator project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'phu!2!9i8iud74)%^j*((rtifo27)lixp)5*)9hkzu)vclx-o1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

SIGNALISATION_APPS = [
    'merkator.spot',
    #'merkator.map',
    #'merkator.administration',
    'merkator',
]

INSTALLED_APPS = [
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'bootstrap3',
    'fontawesome',
    'djangobower',
    'compressor',
    'leaflet',
    'dal',
    'dal_select2',
    'modeltranslation',
] + SIGNALISATION_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'merkator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'merkator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'postgis',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = (
    ('fr', 'Français'),
    ('nl', 'Nederlands'),
    ('en', 'English'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Role

USER_ROLES = (
    'guest',            #only viewing data
    'worker',           #create and manage data
    'manager',          #create and manage data + managing user
)

DEFAULTROLE = 'guest'

ROLES_HERITAGE = {
    'manager' : ('worker', 'guest', ),
    'worker' : ('guest', ),
    'guest' : (),
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = 'static'
STATIC_URL = '/static/'
MEDIA_ROOT = 'media'
MEDIA_URL = '/media/'


# Bower

BOWER_INSTALLED_APPS = (
    'jquery',
    'jquery-ui',
    'bootstrap',
    'modernizr',
    'underscore',
    'nvd3',
    'leaflet.markercluster',
    'leaflet.locatecontrol',
    'fuse',
    'leaflet-pip',
    'twitter-bootstrap-wizard#1.3.2',
    'eonasdan-bootstrap-datetimepicker#latest',
    'typeahead.js',
    'bloodhound',
    'proj4',
)


# Leaflet

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (50.8676041, 4.3737121),
    'DEFAULT_ZOOM': 13,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 20,
    'PLUGINS': {
        'markercluster': {
            'css': ['leaflet.markercluster/dist/MarkerCluster.css','leaflet.markercluster/dist/MarkerCluster.Default.css'],
            'js': 'leaflet.markercluster/dist/leaflet.markercluster.js',
            'auto-include': False,
        },
        'leaflet-pip' :{
            'js' : ['leaflet-pip/leaflet-pip.js'],
            'auto-include': False,
        },
        'locatecontrol' :{
            'css': ['font-awesome/css/font-awesome.min.css','leaflet.locatecontrol/dist/L.Control.Locate.min.css'],
            'js' : ['leaflet.locatecontrol/dist/L.Control.Locate.min.js'],
            'auto-include': False,
        }
    }
}


# Local Settings

APP_INFO = {
    'name': 'Merkator'
}
